version: '3'

volumes:
  pgdata:

services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - /statics/wagtail-agency-personal/static_files:/app/static
      - /statics/wagtail-agency-personal/media_files:/app/media
    ports:
      - 8000:8000
    command: gunicorn -w 4 core.wsgi -b 0.0.0.0:8000
    networks:
      static-network:
        ipv4_address: 172.15.128.2
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: tickets
      POSTGRES_DB: tickets
      POSTGRES_PASS: tickets
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      static-network:
        ipv4_address: 172.15.128.3
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.15.0.0/16

# networks:
#   default:
#     external:
#       name: myNetwork
