# Generated by Django 3.0.11 on 2020-11-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_formfield_clean_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='clean_name',
        ),
    ]
