# Generated by Django 3.0.11 on 2020-11-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('flex', '0011_flexpage_search_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
