# Generated by Django 3.1.3 on 2020-11-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('flex', '0011_flexpage_search_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
