# Generated by Django 3.1.3 on 2020-11-25 14:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0004_homepage_search_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('page_heading_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Super Awesome Section', label='Heading', max_length=80, required=False)), ('description', wagtail.core.blocks.TextBlock(default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', label='Description', max_length=400, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='SEO Text'),
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_text', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='SEO Text')),
                ('content', wagtail.core.fields.StreamField([('page_heading_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Super Awesome Section', label='Heading', max_length=80, required=False)), ('description', wagtail.core.blocks.TextBlock(default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', label='Description', max_length=400, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=False))]))], blank=True, null=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
